### ISSUE TITLE
EasyBuild does not pull required files

### ISSUE THREAD

**Issue by fly-man-** [mangostools/EasyBuild#2]
![cmake-error](https://user-images.githubusercontent.com/115279/48314042-3cba6780-e5c4-11e8-9915-d92220291d88.jpg)

![mysql-error](https://user-images.githubusercontent.com/115279/48314046-3fb55800-e5c4-11e8-8802-7d6532cb7123.jpg)

Correct new version links would be:

MySQL 5.7: http://dev.mysql.com/get/Downloads/MySQLInstaller/mysql-installer-web-community-5.7.24.0.msi

CMake: https://cmake.org/files/v3.12/cmake-3.12.4-win32-x86.msi

**Comment by billy1arm** [comment]
@fly-man- Thanks for the report and update, this repo has been updated
