### ISSUE TITLE
Easybuilder MSB1008 on first try / full source

### ISSUE THREAD

**Issue by wizzymore** [mangostools/EasyBuild#3]
I get this (MSBUILD : error MSB1008: Only one project can be specified. ) when i try to build mangos with EasyBuild ServerTwo

About to run....

C:\Program Files\CMake\bin\cmake.exe  "D:\MangOS\MangOS Two\serverTwo" -DBUILD_TOOLS:BOOL=1 -DBUILD_MANGOSD:BOOL=1 -DBUILD_REALMD:BOOL=1 -DSOAP:BOOL=0 -DSCRIPT_LIB_ELUNA:BOOL=1 -DSCRIPT_LIB_SD3:BOOL=1 -DPLAYERBOTS:BOOL=0 -DCMAKE_INSTALL_PREFIX="D:\MangOS\MangOS Two\serverTwo_install" --build  "D:\MangOS\MangOS Two\serverTwo" -G "Visual Studio 15 Win64"

-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.17134.
-- The C compiler identification is MSVC 19.16.27027.1
-- The CXX compiler identification is MSVC 19.16.27027.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detected 64-bit platform
-- Found Git: C:/Program Files/Git/cmd/git.exe  
-- OpenSSL library: optimized;C:/Program Files/OpenSSL-Win64/lib/VC/ssleay32MD.lib;C:/Program Files/OpenSSL-Win64/lib/VC/libeay32MD.lib;debug;C:/Program Files/OpenSSL-Win64/lib/VC/ssleay32MDd.lib;C:/Program Files/OpenSSL-Win64/lib/VC/libeay32MDd.lib
-- OpenSSL headers: C:/Program Files/OpenSSL-Win64/include
-- OpenSSL version: 1.0.2k
-- Found MySQL library: C:/Program Files/MySQL/MySQL Server 5.6/lib/libmysql.lib
-- Found MySQL headers: C:/Program Files/MySQL/MySQL Server 5.6/include
-- Install server to     : D:/MangOS/MangOS Two/serverTwo_install
-- Install configs to    : D:/MangOS/MangOS Two/serverTwo_install/
-- Search configs from   : binary directory (default)
-- Support for SOAP      : No (default)
-- Script engine Eluna   : Yes (default)
-- Script engine SD3     : Yes (default)
-- Enable Player Bots    : No
-- Build main server     : Yes (default)
-- Build login server    : Yes (default)
-- Build tools           : Yes (default)
-- Build in debug-mode   : No  (default)
-- Configuring done
-- Generating done
-- Build files have been written to: D:/MangOS/MangOS Two/serverTwo_build
VS2017: msBuildPath 64Bit:C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\BinC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin

About to run:C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\msbuild.exe D:\MangOS\MangOS Two\serverTwo_build/INSTALL.vcxproj /p:Platform=x64 /p:VisualStudioVersion=15.0 /tv:15.0 /p:TargetFramework=v15.0 /detailedsummary /v:m /t:Build /maxcpucount /p:Configuration=Release /p:Platform=x64

Build Started: 2/24/2019 2:57:26 AM
Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.
MSBUILD : error MSB1008: Only one project can be specified.
Switch: Two\serverTwo_build/INSTALL.vcxproj
For switch syntax, type "MSBuild /help"

=========================================================
Build Started: 2/24/2019 2:57:26 AM
Build Complete: 2/24/2019 2:57:26 AM
=========================================================

**Comment by billy1arm** [comment]
@wizzymore My apologies for the late reply.
	There is a known bug in easybuild which means the path must not have a space in it

	So instead of having a path: "D:\MangOS\MangOS Two\serverTwo"
	Change this to the following: "D:\MangOS\MangOS_Two\serverTwo" and it should build correctly.
Regards

**Comment by billy1arm** [comment]
This is now checked for and the build prevented.
